src/Entity/Offer.php
<?php

namespace App\Entity;

use App\Repository\OfferRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OfferRepository::class)]
class Offer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 45)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $nbDays = null;

    #[ORM\OneToMany(mappedBy: 'offer', targetEntity: OfferProductType::class, cascade: ['persist','remove'], fetch: 'EAGER')]
    private Collection $offerProductTypes;

    #[ORM\OneToMany( mappedBy: 'offer', targetEntity: SellerOffer::class, cascade: ['persist','remove'])]
    private Collection $sellerOffers;

    public function __construct()
    {
        $this->offerProductTypes = new ArrayCollection();
        $this->sellerOffers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getNbDays(): ?int
    {
        return $this->nbDays;
    }

    public function setNbDays(int $nbDays): self
    {
        $this->nbDays = $nbDays;

        return $this;
    }

    /**
     * @return Collection<int, OfferProductType>
     */
    public function getOfferProductTypes(): Collection
    {
        return $this->offerProductTypes;
    }


    public function getNbProductTypes():int {
        return $this->offerProductTypes->count();
    }

    public function addOfferProductType(OfferProductType $offerProductType): self
    {
        if (!$this->offerProductTypes->contains($offerProductType)) {
            /* $offerProductType->setOffer($this);
             $this->offerProductTypes[] = $offerProductType;*/
           $this->offerProductTypes->add($offerProductType);
             $offerProductType->setOffer($this);
        }

        return $this;
    }

    public function removeOfferProductType(OfferProductType $offerProductType): void
    {
        $this->offerProductTypes->removeElement($offerProductType);
//        if ($this->offerProductTypes->removeElement($offerProductType)) {
//            if ($offerProductType->getOffer() === $this) {
//                $offerProductType->setOffer(null);
//            }
//        }
//
//        return $this;
    }

    /**
     * @return Collection<int, SellerOffer>
     */
    public function getSellerOffers(): Collection
    {
        return $this->sellerOffers;
    }

    public function addSellerOffer(SellerOffer $sellerOffer): self
    {
        if (!$this->sellerOffers->contains($sellerOffer)) {
            $this->sellerOffers->add($sellerOffer);
            $sellerOffer->setOffer($this);
        }

        return $this;
    }


    public function removeSellerOffer(SellerOffer $sellerOffer): self
    {
        if ($this->sellerOffers->removeElement($sellerOffer)) {
            // set the owning side to null (unless already changed)
            if ($sellerOffer->getOffer() === $this) {
                $sellerOffer->setOffer(null);
            }
        }

        return $this;
    }

    public function getPrice():float{
        $price = 0;
        foreach($this->offerProductTypes as $offerProductType)
            $price += $offerProductType->getPrice();
        return $price;
    }

    public function getOfferProductType(ProductType $productType): ?OfferProductType{
        foreach($this->offerProductTypes as $offerProductType)
            if($offerProductType->getProductType() === $productType)
                return $offerProductType;
        return null;
    }


    public function __toString(): string
    {
        // TODO: Implement __toString() method.
        return $this->name;
    }
}

templates/seller_side/base_seller.html.twig
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Title -->
    <title>Home - Andtourtravel </title>
    <!-- Bootstrap css -->
    <link rel="stylesheet" href={{ asset("assets/css/bootstrap.min.css") }} />
    <!-- animate css -->
    <link rel="stylesheet" href="{{ asset('assets/css/animate.min.css') }}">
    <!-- Fontawesome css -->
    <link rel="stylesheet" href={{asset('assets/css/fontawesome.all.min.css')}} />
    <link rel="stylesheet" href= "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css" >
    <!-- popup css -->
    <link rel="stylesheet" href={{ asset("assets/css/popup.css") }} />
    <!-- owl.carousel css -->
    <link rel="stylesheet" href={{ asset("assets/css/owl.carousel.min.css") }} />
    <!-- owl.theme.default css -->
    <link rel="stylesheet" href={{ asset("assets/css/owl.theme.default.min.css") }} />
    <!-- navber css -->
    <link rel="stylesheet" href={{ asset("assets/css/navber.css") }} />
    <!-- meanmenu css -->
    <link rel="stylesheet" href={{ asset("assets/css/meanmenu.css") }} />
    <!-- Style css -->
    <link rel="stylesheet" href={{ asset("assets/css/style.css") }} />
    <!-- Responsive css -->
    <link rel="stylesheet" href={{ asset("assets/css/responsive.css") }} />
    <!-- Favicon -->
    <link rel="icon" type="image/png" href={{ asset("assets/images/favicon.png") }}>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <link rel="stylesheet" href="{{ asset('bundles/mercuryseriesflashy/css/flashy.css') }}">
    {% block stylesheet %}
    {% endblock %}

</head>
<body>
<!-- preloader Area -->
<div class="preloader">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="lds-spinner">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>
        </div>
    </div>
</div>
{{ include('seller_side/partial/header.html.twig') }}


<!-- Banner Area -->
{% block banner %}
{% endblock %}

{% block content %}
{#--------------content goes here--------------#}
{% endblock %}
{{ include('@MercurySeriesFlashy/flashy.html.twig') }}

{#--------------footer--------------#}
    {{ include('seller_side/partial/footer.html.twig') }}
{#--------------end footer--------------#}

{#--------------javascrip--------------#}
{% block javascript %}

<script src={{ asset("assets/js/jquery-3.6.0.min.js") }}></script>
<!-- Bootstrap js -->
<script src={{ asset("assets/js/bootstrap.bundle.js") }}></script>
<!-- Meanu js -->
<script src={{ asset("assets/js/jquery.magnific-popup.min.js") }}></script>
<!-- Meanu js -->
<script src={{ asset("assets/js/jquery.meanmenu.js") }}></script>
<!-- owl carousel js -->
<script src={{ asset("assets/js/owl.carousel.min.js") }}></script>
<!-- wow.js -->
<script src={{ asset("assets/js/wow.min.js") }}></script>
<!-- Custom js -->
<script src={{ asset("assets/js/custom.js") }}></script>
<script src={{ asset("assets/js/add-form.js") }}></script>
<script src={{ asset("assets/js/video.js") }}></script>


{% endblock %}
{#--------------end javascrip--------------#}


</body>

templates/seller_side/dashboard.html.twig
{% extends 'seller_side/base_seller.html.twig' %}
{% block banner %}
    <section id="common_banner">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
{#                    <div class="common_bannner_text">#}
{#                        <h2>Customer dashboard</h2>#}
{#                        <ul>#}
{#                            <li><a href="index.html">Home</a></li>#}
{#                            <li><span><i class="fas fa-circle"></i></span>Customer dashboard</li>#}
{#                        </ul>#}
{#                    </div>#}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block content %}
    <section id="dashboard_main_arae" class="section_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="dashboard_sidebar">
                        <div class="dashboard_sidebar_user">
                            {% if seller.brochureFilename is not null %}
                                <img src="{{ asset('assets/images/' ~ seller.brochureFilename) }}"
                                     onerror="this.src='{{ asset('assets/images/common/dashboard-user.png') }}'" alt="">
                            {% else %}
                                <img src="{{ asset('assets/images/common/dashboard-user.png') }}" alt="">
                            {% endif %}

                            <h3>{{ seller.name }}</h3>
                            <p><a href="">+00 123 456 789</a></p>
                            <p><a href="">{{ seller.user.email }}</a></p>
                        </div>
                        <div class="dashboard_menu_area">
                            <ul>
                                <li><a href="{{ path('app_seller_side_dashboard') }}" class=""><i
                                                class="fas fa-tachometer-alt"></i>Dashboard</a></li>
                                <li class="dashboard_dropdown_button" id="dashboard_dropdowns"><i
                                            class="fas fa-address-card"></i>Offers
                                    <span> <i class="fas fa-angle-down"></i></span>
                                    <div class="booing_sidebar_dashboard" id="show_dropdown_item"
                                         style="display: none;">
                                        <ul>
                                            <li><a href="{{ path('app_seller_side_my_offers') }}"><i
                                                            class="fas fa-hotel"></i>My
                                                    offers</a></li>
{#                                            <li>#}
{#                                                <a href={{ path('app_seller_side_statistics') }}>#}
{#                                                    <i class="fas fa-map"></i>Statistics#}
{#                                                </a>#}
{#                                            </li>#}
{#                                            <li><a href="booking-history.html">#}
{#                                                    <i class="fas fa-history"></i>Booking history</a>#}
{#                                            </li>#}
                                        </ul>
                                    </div>
                                </li>
                                <li><a href="{{ path('app_seller_side_profile') }}" class=""><i class="fas fa-user-circle">
                                        </i>My profile</a>
                                </li>
                                <li><a href={{ path('app_seller_side_statistics') }} ><i class="fas fa-chart-bar">
                                        </i>Statistics</a>
                                </li>
{#                                <li><a href="wallet.html" class=""><i class="fas fa-wallet"></i>Wallet</a></li>#}
{#                                <li><a href="notification.html" class=""><i class="fas fa-bell"></i>Notifications</a></li>#}
                                <li>
                                    <a href="#" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                        <i class="fas fa-sign-out-alt"></i>Logout
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div id="dynamic_content"
                {% block dynamic_content %}
                    <!-- ------------content goes here-------------- -->
                {% endblock %}
            </div>
        </div>
    </section>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body logout_modal_content">
                    <div class="btn_modal_closed">
                        <button type="button" data-bs-dismiss="modal" aria-label="Close"><i
                                    class="fas fa-times"></i></button>
                    </div>
                    <h3>
                        Are you sure? <br>
                        you want to log out.
                    </h3>
                    <div class="logout_approve_button">
                        <button data-bs-dismiss="modal" class="btn btn_theme btn_md" id="logout-confirm-btn" href="{{ path('app_logout') }}">Yes Confirm</button>
                        <button data-bs-dismiss="modal" class="btn btn_border btn_md">No Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        //set a tag to active if it is active
        $(document).ready(function () {
            let activePage = window.location.href;
            $('.dashboard_menu_area ul li a').each(function () {
                let linkPage = this.href;
                if (activePage === linkPage) {
                    $(this).addClass("active");
                }
            });
        });
    </script>

    <script>
        document.getElementById("logout-confirm-btn").addEventListener("click", function() {
            fetch("/logout", { method: "POST" })
                .then(function(response) {
                    // Handle the logout response
                    // Example: Redirect to the homepage after logout
                    window.location.href = "/";
                })
                .catch(function(error) {
                    console.error("Logout failed:", error);
                });
        });
    </script>
{% endblock %}

templates/seller_side/login.html.twig
{% extends 'seller_side/base_seller.html.twig' %}

{% block banner %}
    <!-- Common Banner Area -->
    <section id="common_banner">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="common_bannner_text">
                        <h2>Login</h2>
                        <ul>
                            <li><a href="index.html">Home</a></li>
                            <li><span><i class="fas fa-circle"></i></span> Login</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block content %}

    <!--  Common Author  -->
    <section id="common_author_area" class="section_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <div class="common_author_boxed">
                        <div class="common_author_heading">
                            <h3>Login your account</h3>
                            <h2>Logged in to stay in touch</h2>
                        </div>
                        <div class="common_author_form">
                            <form action="#" id="main_author_form">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Enter user name" />
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control" placeholder="Enter password" />
                                    <a href="forgot-password.html">Forgot password?</a>
                                </div>
                                <div class="common_form_submit">
                                    <button class="btn btn_theme btn_md">Log in</button>
                                </div>
                                <div class="have_acount_area">
                                    <p>Dont have an account? <a href={{ path('app_seller_side_subscription') }}>Register now</a></p>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {{ include('seller_side/ourProudcts.html.twig') }}
{% endblock %}

templates/seller_side/sellerCard.html.twig
{% extends 'seller_side/base_seller.html.twig' %}

{% block banner %}
    <section id="common_banner">
    </section>
{% endblock %}

{% block content %}

    {% if selectedOffers is defined and app.session.has('selectedOffers') and app.session.get('selectedOffers')|length != 0 %}
        {% set totalPrice = 0 %}
        <section id="tour_details_main" class="section_padding">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="tour_details_leftside_wrapper">
                            <div class="tour_details_heading_wrapper">
                                <div class="tour_details_top_heading">
                                    <h2>Cart</h2>
                                </div>
                            </div>

                            {% for message in app.flashes('error') %}
                                <div class="alert alert-light d-flex align-items-center alert-dismissible fade show border-danger"
                                     role="alert">
                                    <i class="bi bi-x-circle-fill text-danger me-2"></i>
                                    <span>{{ message }}</span>
                                    <button type="button" class="btn-close" data-bs-dismiss="alert"
                                            aria-label="Close"></button>
                                </div>
                            {% endfor %}

                            {% for message in app.flashes('success') %}
                                <div class="alert alert-light d-flex align-items-center alert-dismissible fade show border-success"
                                     role="alert">
                                    <i class="bi bi-check-circle-fill text-success me-2"></i>
                                    <span>{{ message }}</span>
                                    <button type="button" class="btn-close" data-bs-dismiss="alert"
                                            aria-label="Close"></button>
                                </div>
                            {% endfor %}

                            {% set nbOffer = 0 %}
                            {% for index in 0..selectedOffers|length-1 %}
                                {% set nbOffer = nbOffer + 1 %}
                                {% set offer = selectedOffers[index] %}
                                {% set form = forms[index] %}

                                {% set offerPrice = 0 %}
                                <div class="tour_details_boxed">
                                    <h3 class="heading_theme">Offer: {{ offer.name }} <p>validity: ({{ offer.nbDays }}
                                            days)</p></h3>
                                    <div class="tour_details_boxed_inner">
                                        <div class="card_container">
                                            <div class="card_box">
                                                <h5>Including products ({{ offer.nbProductTypes }})</h5>
                                                <ul>
                                                    {% for offerProductType in  offer.offerProductTypes %}
                                                        {% set offerPrice = offerPrice + offerProductType.price %}
                                                        {% set totalPrice = totalPrice + offerProductType.price %}

                                                        <div class="tour_details_top_heading_right">
                                                            <p style="display: inline" class="font-weight-bold">
                                                                🞄 {{ offerProductType.productType.name }} : </p>
                                                            <p style="display: inline">&nbsp;Max
                                                                items: {{ offerProductType.maxItems }} &nbsp;|&nbsp;
                                                                Price: {{ offerProductType.price }}</p>
                                                        </div>

                                                    {% endfor %}
                                                </ul>
                                            </div>

                                            <div class="card_box ">
                                                <!--  date form -->
                                                <div class="col-lg-10 col-md-8 col-sm-12 col-12">
                                                    <div class="flight_Search_boxed date_flex_area">
                                                        {{ form_start(form, { 'attr': {'class': 'offer-form'} }) }}
                                                        {{ form_widget(form) }}
                                                        {{ form_end(form) }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card_container">
                                        <div class="card_box">
                                            <p>Offer price: {{ offerPrice }}</p>
                                            <a class=""
                                               href="{{ path('app_seller_side_removeFromCard',{'id': offer.id}) }}">
                                                <i class="bi bi-trash"></i>Remove item</a>

                                        </div>
                                        <div class="card_box right-align">

                                        </div>
                                    </div>
                                    <div class="edit_person">

                                    </div>


                                </div>
                            {% endfor %}

                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="tour_details_right_sidebar_wrapper">
                            <div class="tour_detail_right_sidebar">
                                <div class="tour_details_right_boxed">
                                    <div class="tour_details_right_box_heading">
                                        <h3>Details</h3>
                                    </div>
                                    <div class="tour_package_details_bar_list">

                                        <ul>
                                            <li><i class="fas fa-circle"></i>Total offers ({{ nbOffer }})</li>
                                            <li><i class="fas fa-circle"></i>Others details</li>

                                        </ul>
                                    </div>
                                    <div class="tour_package_details_bar_price">
                                        <h5>Total price</h5>
                                        <div class="tour_package_bar_price">
                                            <h6>
                                                <del></del>
                                            </h6>
                                            <h3> {{ totalPrice }} <sub>TND</sub></h3>
                                        </div>
                                    </div>
                                </div>
                                <div class="tour_select_offer_bar_bottom">
                                    <button class="btn btn_theme btn_md w-100" data-bs-toggle="modal"
                                            data-bs-target="#exampleModal"
                                            id="submit-all-forms">Buy
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    {% else %}
        <div class="d-flex justify-content-center">
            <div class="tour_details_boxed col-lg-10">
                <div style="margin-left: 38%">
                    <img class="" style="" src="{{ asset('assets/images/emptyCard.png') }}">
                </div>
                <p class="top_form_search_button">You didn't choose any offer, you can pick one here</p>
                <div class="top_form_search_button">
                    <a href="{{ path('app_seller_side_offer') }}">
                        <button class="btn btn_theme btn_md">List of offers</button>
                    </a>
                </div>
            </div>
        </div>
    {% endif %}



    <!-- Buy Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body logout_modal_content">
                    <div class="btn_modal_closed">
                        <button type="button" data-bs-dismiss="modal" aria-label="Close"><i class="fas fa-times"></i></button>
                    </div>
                    <h3>Buying process</h3>


                    <div class="vendor_form col-lg-10 d-flex flex-column align-items-center">
                        <div class="form-group input-margin">
                            <label for="name" class="col-form-label mb-2">Name:</label>

                                <input type="text" class="form-control" id="name" placeholder="Enter your name" required>

                        </div>
                        <div class="form-group input-margin">
                            <label for="email" class="col-form-label mb-2">Email:</label>

                                <input type="email" class="form-control" id="email" placeholder="Enter your email" required>

                        </div>
                        <div class="form-group input-margin">
                            <label for="phone" class="col-form-label mb-2">Phone:</label>

                                <input type="tel" class="form-control" id="phone" placeholder="Enter your phone number" required>

                        </div>

                    </div>
                    <div class="logout_approve_button">
                        <button data-bs-dismiss="modal" class="btn btn_theme btn-md" id="logout-confirm-btn">Buy</button>
                        <button data-bs-dismiss="modal" class="btn btn_border btn-md">No Cancel</button>
                    </div>
                </div>
        </div>
    </div>


    <script>
        $(function () {
            document.getElementById('logout-confirm-btn').addEventListener('click', function () {
                let formData = {};
                let isFormValid = true; // add a variable to check if all required fields are filled out
                $('.offer-form').each(function () {
                    let formFields = $(this).serializeArray();
                    formFields.forEach(function (field) {
                        if (field.value.trim() === '') { // check if the field is empty or only contains spaces
                            isFormValid = false; // set the flag to false if any required field is empty
                        }
                        formData[field.name] = field.value;
                    });
                });
                if (isFormValid) { // only send the data if all required fields are filled out
                    $.ajax({
                        type: 'POST',
                        url: '{{ path('app_seller_side_buyOffer') }}',
                        data: formData,
                        success: function (response) {
                            console.log('Success: ' + JSON.stringify(response));
                            // redirect to the new page
                            window.location.href = response.newPageUrl;
                            document.getElementById('logout-confirm-btn').removeEventListener('click', this);
                        },
                        error: function (response) {
                            console.log('Error: ' + JSON.stringify(response));
                        }
                    });
                    isFormValid = false;
                } else {
                    console.log('date no valid')
                }
            });
        });
    </script>

    <style>
        .input-margin {
            margin-top: 10px;
            margin-bottom: 10px;
        }

        .form-control{

        }
    </style>

    <style>
        .card_container {
            display: flex;
            flex-direction: row;
        }

        .card_box {
            width: 50%;
            padding: 0 0 10px;
            margin: 0 auto 5px 0;
        }

        .right-align {
            text-align: right;
        }
    </style>

{% endblock %}